### ISSUE TITLE
Parent finally block does not run 

### ISSUE THREAD

**Issue by nvlled** [wraikny/AwaitableCoroutine#14]
I'm using Coroutines with finally to clean up and remove and handlers when coroutine is cancelled. It works fine when I tried using regular Task, but not with Coroutine:

```c#
public void TestAwaitable()
{
    var runner = new CoroutineRunner();
    var co = runner.Create(async () =>
    {
        try
        {

            await Fn();
        }
        finally
        {
            // this won't get printed
            Console.WriteLine("finally A");
        }
    });

    while (!co.IsCompleted)
    {
        runner.Update();
    }
}

public async Coroutine Fn()
{
    try
    {
        await Coroutine.DelayCount(100);
        throw new Exception();
    }
    finally
    {
        // this gets printed
        Console.WriteLine("finally B");
    }
}
```

**Comment by wraikny** [comment]
Thanks for the report. I will investigate it.

**Comment by wraikny** [comment]
@nvlled Added implementation of exception propagation with `await`. However, it is wrapped by `ChildCanceledException` to distinguish which coroutine raised the exception. Use the `InnerException` property to get the original exception.
Version 1.8.0 is now available via NuGet.

**Comment by nvlled** [comment]
Awesome! It works for me now. Thanks.

While I'm at it, is there any example usage for cancelling deeply nested coroutines? Not sure if I ran into some other bugs, or if I'm just doing something wrong (before 1.8.0).

**Comment by wraikny** [comment]
@nvlled 

I'm sorry, I don't understand what you are saying. 

If you want to use `try ~ catch ~ finally`, please use 1.8.0.

It's possible to write as follows in 1.7, however, it isn't a good code because it's semantically non-trivial.

```csharp
var parent = runner.Create(async () => {
    var child = await Coroutine.Lambda(async () => {
        await coroutine1;
        await coroutine2;
    });
    
    // like await
    while (!child.IsCompleted) await Coroutine.Yield();

    /* do something like finally */

    // early return
    if (child.IsCanceled) return;

    /* do something continuation */
});
```

(As a side note, `IsCanceled` in 1.7 is the same as `IsCanceledOrFaulted` in 1.8 because I added `IsFaulted` in 1.8.)

**Comment by nvlled** [comment]
Yeah, disregard what I said, it works fine now.
